
#define TheSampleLine_code_pure 2

#define TheSampleLine_withComment1 3//with comment case 1 /* 110906 HFZ@SSS [v20.50][PreAlpha][Add][AddNewDevice_Marlow] */

#define TheSampleLine_withComment2 3/*with comment case 2 */

#define TheSampleLine_withComment3 3/*with comment case 3
multible line
 */

// #define LINETYPE_COMMENT_SINGLE			4 Single Comment line
/* #define LINETYPE_COMMENT_SINGLE			4 Single Comment line*/

/* #define LINETYPE_COMMENT_SINGLE			4 Single Comment line
Line 1
Line 2
Line 3
*/

/* 100906 ZHF@SSS [v20.50][PreAlpha][Add][AddNewDevice_Marlow] Start */
static OBJECTIVETABLE PrintImageE320_VIVID[] = {
	{ IDR_STR_PRINTIMAGE_GENERAL, ID_QUASELECTION_GENERAL, IDR_STR_ACCOUNT_PRINTIMAGE_GENERAL },
	{ IDR_STR_PRINTIMAGE_DTP, ID_QUASELECTION_DTP, IDR_STR_ACCOUNT_PRINTIMAGE_DTP },
	{ IDR_STR_PRINTIMAGE_GRAPHICS, ID_QUASELECTION_GRAPHICS, IDR_STR_ACCOUNT_PRINTIMAGE_GRAPHICS },
	{ IDR_STR_PRINTIMAGE_VIVID, ID_QUASELECTION_PHOTO, IDR_STR_ACCOUNT_PRINTIMAGE_PHOTO },
	{ IDR_STR_PRINTIMAGE_CAD, ID_QUASELECTION_CAD, IDR_STR_ACCOUNT_PRINTIMAGE_CAD },
	{ IDR_STR_PRINTIMAGE_OTHER, ID_QUASELECTION_OTHER, IDR_STR_ACCOUNT_PRINTIMAGE_OTHER }
};
/* 100906 ZHF@SSS [v20.50][PreAlpha][Add][AddNewDevice_Marlow] End */


/* 100906 ZHF@SSS [v20.50][PreAlpha][Add][AddNewDevice_Marlow] Start */
static OBJECTIVETABLE PrintImageE320_VIVID[] = {
	{ IDR_STR_PRINTIMAGE_GENERAL, ID_QUASELECTION_GENERAL, IDR_STR_ACCOUNT_PRINTIMAGE_GENERAL },
	{ IDR_STR_PRINTIMAGE_DTP, ID_QUASELECTION_DTP, IDR_STR_ACCOUNT_PRINTIMAGE_DTP },
	{ IDR_STR_PRINTIMAGE_GRAPHICS, ID_QUASELECTION_GRAPHICS, IDR_STR_ACCOUNT_PRINTIMAGE_GRAPHICS },
	{ IDR_STR_PRINTIMAGE_VIVID, ID_QUASELECTION_PHOTO, IDR_STR_ACCOUNT_PRINTIMAGE_PHOTO },/* 110906 HFZ@SSS [v20.50][PreAlpha][Add][AddNewDevice_Marlow] */
	{ IDR_STR_PRINTIMAGE_CAD, ID_QUASELECTION_CAD, IDR_STR_ACCOUNT_PRINTIMAGE_CAD },
	{ IDR_STR_PRINTIMAGE_OTHER, ID_QUASELECTION_OTHER, IDR_STR_ACCOUNT_PRINTIMAGE_OTHER }
};
/* 100906 ZHF@SSS [v20.50][PreAlpha][Add][AddNewDevice_Marlow] End */


/* 100906 ZHF@SSS [v20.50][PreAlpha][Add][AddNewDevice_Marlow] Start */
static OBJECTIVETABLE PrintImageE320_VIVID[] = {
	{ IDR_STR_PRINTIMAGE_GENERAL, ID_QUASELECTION_GENERAL, IDR_STR_ACCOUNT_PRINTIMAGE_GENERAL },
	{ IDR_STR_PRINTIMAGE_DTP, ID_QUASELECTION_DTP, IDR_STR_ACCOUNT_PRINTIMAGE_DTP },
	{ IDR_STR_PRINTIMAGE_GRAPHICS, ID_QUASELECTION_GRAPHICS, IDR_STR_ACCOUNT_PRINTIMAGE_GRAPHICS },
/* 110906 HFZ@SSS [v20.50][PreAlpha][Add][AddNewDevice_Marlow] Start */
	{ IDR_STR_PRINTIMAGE_VIVID, ID_QUASELECTION_PHOTO, IDR_STR_ACCOUNT_PRINTIMAGE_PHOTO },
	{ IDR_STR_PRINTIMAGE_CAD, ID_QUASELECTION_CAD, IDR_STR_ACCOUNT_PRINTIMAGE_CAD },
/* 110906 HFZ@SSS [v20.50][PreAlpha][Add][AddNewDevice_Marlow] End */
	{ IDR_STR_PRINTIMAGE_OTHER, ID_QUASELECTION_OTHER, IDR_STR_ACCOUNT_PRINTIMAGE_OTHER }
};
/* 100906 ZHF@SSS [v20.50][PreAlpha][Add][AddNewDevice_Marlow] End */


/* 100906 ZHF@SSS [v20.50][PreAlpha][Add][AddNewDevice_Marlow] Start */
static OBJECTIVETABLE PrintImageE320_VIVID[] = {
	{ IDR_STR_PRINTIMAGE_GENERAL, ID_QUASELECTION_GENERAL, IDR_STR_ACCOUNT_PRINTIMAGE_GENERAL },
	{ IDR_STR_PRINTIMAGE_DTP, ID_QUASELECTION_DTP, IDR_STR_ACCOUNT_PRINTIMAGE_DTP },
	{ IDR_STR_PRINTIMAGE_GRAPHICS, ID_QUASELECTION_GRAPHICS, IDR_STR_ACCOUNT_PRINTIMAGE_GRAPHICS },
	/* 110906 HFZ@SSS [v20.50][PreAlpha][Add][AddNewDevice_Marlow] Start */
	{ IDR_STR_PRINTIMAGE_VIVID, ID_QUASELECTION_PHOTO, IDR_STR_ACCOUNT_PRINTIMAGE_PHOTO },
	{ IDR_STR_PRINTIMAGE_CAD, ID_QUASELECTION_CAD, IDR_STR_ACCOUNT_PRINTIMAGE_CAD },
/* 100906 ZHF@SSS [v20.50][PreAlpha][Add][AddNewDevice_Marlow] End */
	{ IDR_STR_PRINTIMAGE_OTHER, ID_QUASELECTION_OTHER, IDR_STR_ACCOUNT_PRINTIMAGE_OTHER }
};
	/* 110906 HFZ@SSS [v20.50][PreAlpha][Add][AddNewDevice_Marlow] End */

/* 100906 ZHF@SSS [v20.50][PreAlpha][Add][AddNewDevice_Marlow] Start */
static OBJECTIVETABLE PrintImageE320_VIVID[] = {
	{ IDR_STR_PRINTIMAGE_GENERAL, ID_QUASELECTION_GENERAL, IDR_STR_ACCOUNT_PRINTIMAGE_GENERAL },
	{ IDR_STR_PRINTIMAGE_DTP, ID_QUASELECTION_DTP, IDR_STR_ACCOUNT_PRINTIMAGE_DTP },
	{ IDR_STR_PRINTIMAGE_GRAPHICS, ID_QUASELECTION_GRAPHICS, IDR_STR_ACCOUNT_PRINTIMAGE_GRAPHICS },
	/* 100906 HFZ@SSS [v20.50][PreAlpha][Add][AddNewDevice_Marlow] Start */
	{ IDR_STR_PRINTIMAGE_VIVID, ID_QUASELECTION_PHOTO, IDR_STR_ACCOUNT_PRINTIMAGE_PHOTO },
	{ IDR_STR_PRINTIMAGE_CAD, ID_QUASELECTION_CAD, IDR_STR_ACCOUNT_PRINTIMAGE_CAD },
	/* 100906 ZHF@SSS [v20.50][PreAlpha][Add][AddNewDevice_Marlow] End */
	{ IDR_STR_PRINTIMAGE_OTHER, ID_QUASELECTION_OTHER, IDR_STR_ACCOUNT_PRINTIMAGE_OTHER }
};
/* 100906 HFZ@SSS [v20.50][PreAlpha][Add][AddNewDevice_Marlow] End */


$FNS_FnMethod_STAPLE(HIDE) :-true./* 100227 ZMJ@SSS[v21.25][PreAlpha][Add][GCRSpecChange] */ /* 110227 ZMJ@SSS[v21.25][PreAlpha][Add][GCRSpecChange] */ /* 140227 ZMJ@SSS[v21.25][PreAlpha][Add][GCRSpecChange] */ /* 120227 ZMJ@SSS[v21.25][PreAlpha][Add][GCRSpecChange] */

// #if defined(JP) | (JPE)	/* 140220 JJJ@SSS [v21.25][PreAlpha][Delete][Kabul_2] */		
$FNS_FnMethod_STAPLE(HIDE) :-true.
$FNS_FnMethod_STAPLEGROUP(HIDE) : -true.
// #endif	/* 140220 JJJ@SSS [v21.25][PreAlpha][Delete][Kabul_2] */

#include "attenum.h"	/* For "ID_STATE3_DISABLE" */	/* 131209 DWY@SSS [v21.20][PreAlpha][Add][Common_CR000080] */
#define QUERY_COLR_100GCRPROFILE_COMBO_SUPPORT		0x10000020		/* [Color]シートで[100%GCRプロファイルを使用する]コンボボックスサポート機種 */			/* 140227 ZMJ@SSS[v21.25][PreAlpha][Add][GCRSpecChange] */

/* 140214 GJG@SSS [v21.25][PreAlpha][Add][AddNewDevice_Kabul] Start */
IDM_IRC1335,						/* Reykjavik */
0, 0, 1, 1,
L"CNCH10A.ICC",                     /* Destination Profile */
L"CNCH10B.ICC",                     /* Destination Profile *
/* 140214 GJG@SSS [v21.25][PreAlpha][Add][AddNewDevice_Kabul] End */

//#if 1	/* 090313 SAI@IST add start for PCL_i_QA V20.00-00026 *//* 100705 ISA@IST mod [#if 0]->[#if 1] for V20.35_00023 */
